# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\win_inet_pton-feedstock\recipe, last modified Tue Jul  3 15:56:31 2018
# ------------------------------------------------

package:
    name: win_inet_pton
    version: 1.0.1
source:
    fn: win_inet_pton-1.0.1.tar.gz
    sha256: a45bc3073469afb5afd0e395aaabd836040a20ba1f2a6dd1196fa2b210ba386e
    url: https://pypi.io/packages/source/w/win_inet_pton/win_inet_pton-1.0.1.tar.gz
build:
    number: '1'
    script: python setup.py install
    string: py37_1
requirements:
    build:
        - python 3.7.0 hea74fb7_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - win_inet_pton
about:
    dev_url: https://github.com/hickeroar/win_inet_pton
    home: https://github.com/hickeroar/win_inet_pton
    license: PUBLIC-DOMAIN
    license_file: LICENSE
    summary: Native inet_pton and inet_ntop implementation for Python on Windows (with
        ctypes).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
