# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# C:\ci\containers\00003mmnqrk\tmp\build\80754af9\rsync-recipes\ca-certificates-2018.03.07-on-winbuilder, last modified Mon Apr  2 14:29:57 2018
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2018.03.07
source:
    fn: cacert.pem
    sha256: 79ea479e9f329de7075c40154c591b51eb056d458bc4dff76d9a4b9c6c4f6d0b
    url: https://curl.haxx.se/ca/cacert-2018-03-07.pem
build:
    commands:
        - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
        - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
        - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
    string: '0'
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
