# This file created by conda-build 3.1.6+534.g828a654f1.dirty
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\wheel-feedstock\recipe, last modified Tue Jun 26 11:13:45 2018
# ------------------------------------------------

package:
    name: wheel
    version: 0.31.1
source:
    fn: wheel-0.31.1.tar.gz
    sha256: 0a2e54558a0628f2145d2fc822137e322412115173e8a2ddbe1c9024338ae83c
    url: https://pypi.io/packages/source/w/wheel/wheel-0.31.1.tar.gz
build:
    entry_points:
        - wheel = wheel.tool:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - certifi 2018.4.16 py37_0
        - python 3.7.0 hea74fb7_0
        - setuptools 39.2.0 py37_0
        - vc 14 h0510ff6_3
        - vs2015_runtime 14.0.25123 3
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
        - wheel.signatures
        - wheel.tool
about:
    home: https://bitbucket.org/pypa/wheel/
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
