# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\cffi-feedstock\recipe, last modified Tue Aug 14 02:11:49 2018
# ------------------------------------------------

package:
    name: cffi
    version: 1.11.5
source:
    patches:
        - 0001-Link-to-dl-library.patch
    sha256: e90f17980e6ab0f3c2f3730e56d1fe9bcba1891eeea58966e89d352492cc74f4
    url: https://pypi.io/packages/source/c/cffi/cffi-1.11.5.tar.gz
build:
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py37h74b6da3_1
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - certifi 2018.4.16 py37_0
        - pip 10.0.1 py37_0
        - pycparser 2.18 py37_1
        - python 3.7.0 hea74fb7_0
        - setuptools 40.0.0 py37_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
        - wheel 0.31.1 py37_0
        - wincertstore 0.2 py37_0
    run:
        - pycparser
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    imports:
        - _cffi_backend
        - cffi
    requires:
        - openssl
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - jschueller
        - mingwandroid
        - ocefpaf
